name: Build & deploy Spring Boot app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy Spring Boot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run Unit Tests
        run: mvn -B test  # Supprimé 'pom.xml' qui causait l'erreur

      - name: Build the application
        run: mvn -B clean package  # Combiné en une seule commande